name: Build and Push to ECR

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Build backend
      - name: Build backend image
        run: docker build -t ${{ secrets.ECR_REPOSITORY }} -f server/Dockerfile server

      - name: Tag backend image
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY }}:latest ${{ secrets.ECR_REPOSITORY }}:latest

      - name: Push backend image
        run: |
          docker push ${{ secrets.ECR_REPOSITORY }}:latest

      # Build frontend
      - name: Build frontend image
        run: docker build -t ${{ secrets.ECR_REPOSITORY_FRONT }} -f client/Dockerfile client

      - name: Tag frontend image
        run: |
          docker tag ${{ secrets.ECR_REPOSITORY_FRONT }}:latest ${{ secrets.ECR_REPOSITORY_FRONT }}:latest

      - name: Push frontend image
        run: |
          docker push ${{ secrets.ECR_REPOSITORY_FRONT }}:latest

      # Deploy backend (API)
      - name: Deploy backend to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: test-mytest-api-td-revision1.json
          service: test-mytest-api-td-service-1
          cluster: test-mytest-front
          wait-for-service-stability: true

      # Deploy frontend
      - name: Deploy frontend to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: test-mytest-front-td-revision2.json
          service: test-mytest-front-td-service-5cd7i03c
          cluster: test-mytest-front
          wait-for-service-stability: true